FROM xosproject/xos-synchronizer-base:candidate

ADD . /opt/xos/synchronizers/vtn

ADD __init__.py /opt/xos/services/__init__.py
ADD __init__.py /opt/xos/services/vtn/__init__.py
ADD tmp.vtnnetport.py /opt/xos/services/vtn/vtnnetport.py

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/vtn"

CMD bash -c "cd /opt/xos/synchronizers/vtn; ./run-from-api.sh"
